version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./era5:/app/era5
      - ./utils:/app/utils
      - ./station:/app/station
      - ./infilling:/app/infilling
      - ./train_station_twin:/app/train_station_twin
      - ./web_interface:/app/web_interface
    deploy:
        resources:
          limits:
            memory: 12G
  nginx:
    image: nginx:1.19.6-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web_interface:/usr/share/nginx/html
    command: [nginx-debug, '-g', 'daemon off;']
    network_mode: host
    restart: always